"""Type stubs for ics.event module."""

from typing import Optional, Union, Any
from datetime import date, datetime

class Event:
    """iCal Event class."""
    
    def __init__(self) -> None: ...
    
    @property
    def name(self) -> Optional[str]: ...
    @name.setter
    def name(self, value: str) -> None: ...
    
    @property
    def begin(self) -> Optional[Union[date, datetime]]: ...
    @begin.setter  
    def begin(self, value: Union[date, datetime]) -> None: ...
    
    @property
    def description(self) -> Optional[str]: ...
    @description.setter
    def description(self, value: str) -> None: ...
    
    @property
    def location(self) -> Optional[str]: ...
    @location.setter
    def location(self, value: str) -> None: ...
    
    def make_all_day(self) -> None: ...
    def serialize(self) -> str: ...
    def clone(self) -> "Event": ...
    
    # Additional methods that may be used
    def add_attendee(self, attendee: Any) -> None: ...
    def ends_within(self, other: Any) -> bool: ...
    def has_end(self) -> bool: ...
    def includes(self, other: Any) -> bool: ...
    def intersects(self, other: Any) -> bool: ...
    def is_included_in(self, other: Any) -> bool: ...
    def join(self, other: Any) -> Any: ...
    def serialize_iter(self) -> Any: ...
    def starts_within(self, other: Any) -> bool: ...
    def time_equals(self, other: Any) -> bool: ...